insert into film_genre SELECT 1, id as film, 1 FROM film WHERE name = 'Отряд самоубийц';
insert into film_genre SELECT 2, id as film, 11 FROM film WHERE name = 'Отряд самоубийц';
insert into film_genre SELECT 3, id as film, 14 FROM film WHERE name = 'Отряд самоубийц';
insert into film_genre SELECT 4, id as film, 1 FROM film WHERE name = 'Чудо-женщина';
insert into film_genre SELECT 5, id as film, 11 FROM film WHERE name = 'Чудо-женщина';
insert into film_genre SELECT 6, id as film, 14 FROM film WHERE name = 'Чудо-женщина';
insert into film_genre SELECT 7, id as film, 1 FROM film WHERE name = 'Бэтмен против Супермена: На заре справедливости';
insert into film_genre SELECT 8, id as film, 11 FROM film WHERE name = 'Бэтмен против Супермена: На заре справедливости';
insert into film_genre SELECT 9, id as film, 14 FROM film WHERE name = 'Бэтмен против Супермена: На заре справедливости';
insert into film_genre SELECT 10, id as film, 1 FROM film WHERE name = 'Первый мститель: Противостояние';
insert into film_genre SELECT 11, id as film, 11 FROM film WHERE name = 'Первый мститель: Противостояние';
insert into film_genre SELECT 12, id as film, 14 FROM film WHERE name = 'Первый мститель: Противостояние';
insert into film_genre SELECT 13, id as film, 1 FROM film WHERE name = 'Мстители';
insert into film_genre SELECT 14, id as film, 11 FROM film WHERE name = 'Мстители';
insert into film_genre SELECT 15, id as film, 14 FROM film WHERE name = 'Мстители';
insert into film_genre SELECT 16, id as film, 1 FROM film WHERE name = 'Люди Икс: Апокалипсис';
insert into film_genre SELECT 17, id as film, 11 FROM film WHERE name = 'Люди Икс: Апокалипсис';
insert into film_genre SELECT 18, id as film, 14 FROM film WHERE name = 'Люди Икс: Апокалипсис';

